# Generated by Django 4.0.8 on 2024-03-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_figure_alter_quiz_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
    ]
