# Generated by Django 4.0.8 on 2024-04-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_code_remove_course_credit_and_more'),
        ('quiz', '0005_alter_mcquestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': 'Multiple Choice Question', 'verbose_name_plural': 'Multiple Choice Questions'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'User Score', 'verbose_name_plural': 'User score records'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answers_at_end',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='exam_paper',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pass_mark',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='single_attempt',
        ),
        migrations.RemoveField(
            model_name='sitting',
            name='course',
        ),
        migrations.AddField(
            model_name='progress',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='progress',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='time_spent',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.TextField(blank=True, choices=[('fill_in_gaps', 'Fill in gaps Quiz'), ('true_false', 'True or False Quiz'), ('MCQ', 'MCQ Quiz')]),
        ),
    ]
