# Generated by Django 4.0.8 on 2024-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
      
    ]
