# Generated by Django 4.0.8 on 2024-03-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsandevents_updated_date_newsandevents_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
